const board = {
  boards: {
    "2025-2026": {
      members: [
        {
          name: "Kwasi Fosu",
          position: "President",
          img: "images/eboard-photos/kwasi-pic.jpg",
          bio: "My name is Kwasi Fosu and I’m the President of ColorStack OSU. On the technical side I’ve had 1 internship with Mastercard as a SWE focusing on Machine Learning, and will be returning as a full-time engineer. On the non-technical side I enjoy things such as traveling, photography, and cooking. Feel free to reach out!",
          linkedin: "https://www.linkedin.com/in/kwasi-sarfo-fosu-21a179255/",
        },
        {
          name: "Kobe Jenkins",
          position: "Vice President",
          img: "images/eboard-photos/kobe-pic.jpg",
          bio: "My name is Kobe, and I’m the vice president for ColorStack. I’m a Data Analytics Major, and last summer I worked as a data intern at Hyperion materials and technologies, this summer, I’ll be joining Capital One as a Data Analyst. Some of my hobbies are playing basketball and going out. If you have any data related questions, or any questions in general, please feel free to ask.",
          linkedin: "https://www.linkedin.com/in/kobejenkins/",
        },
        {
          name: "Arielle Barnes",
          position: "Secretary",
          img: "images/eboard-photos/arielle-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ariellebarnes/",
        },
        {
          name: "Rania Omer",
          position: "Treasurer",
          img: "images/eboard-photos/rania-pic.jpg",
          bio: "Hi, my name is Rania Omer, and I serve as the Treasurer for ColorStack @ OSU! I major in Computer Science and Engineering with a minor in Studio Art. I’ve previously interned at Microsoft and will be returning this summer as a SWE Intern. I’m also currently working as a Web Dev Intern at OSU. I’ve been involved in orgs and programs like MLT, MSP, MTC, BlackXBold, and Girls Who Code. Outside of school and work, I enjoy reading, painting, photography, and traveling. Happy to chat about technical and professional experiences, study abroad opportunities, or anything else I mentioned!",
          linkedin: "https://www.linkedin.com/in/raniaomer/",
        },
        {
          name: "Austen Young",
          position: "Media & Web Development",
          img: "images/eboard-photos/austen-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/austenyoung/",
        },

        {
          name: "Hosanna Otchere",
          position: "Communications",
          img: "images/eboard-photos/hosanna-pic.jpg",
          bio: "Hi, my name is Hosanna Otchere, I am the Communications Chair.  I’ve had a few experiences, conducted research in video summarization, completed an internship at Mastercard, and I’m an Adobe Student Ambassador. Outside of that, I like wellness, music, and sometimes video editing. Hit me up, if you have any questions about getting into research, internships, graphics, or video editing. ",
          linkedin: "https://www.linkedin.com/in/hosannaao/",
        },

        {
          name: "Raul Mainsah",
          position: "Operations",
          img: "images/eboard-photos/raul-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/raul-lamar-mainsah/",
        },

        {
          name: "Valdez Kankeu",
          position: "Corporate",
          img: "images/eboard-photos/valdez-pic.jpg",
          bio: "Hello my name is Valdez Kankeu, and I’m a 2nd-year Computer Science & Engineering student currently serving as the Corporate Chair for ColorStack. I’m heading into this summer as a software engineering intern at GoDaddy! When I’m not busy with tech or my responsibilities on campus, you can usually find me hitting the gym or out socializing. I’m always looking to expand my network and meet new people feel free to reach out!",
          linkedin: "https://www.linkedin.com/in/valdez-kankeu/",
        },

        {
          name: "Harith Madani",
          position: "Outreach",
          img: "images/eboard-photos/harith-pic.jpg",
          bio: "My name is Harith Madani and I’m a junior cse student and the outreach for ColorStack. I’ve previously interned in swe roles with JPMorgan Chase and SEO Tech Developer and I’m currently an intern at HubSpot. I also love travel, watching movies, and playing sports. Feel free to hit me up to discuss internships, career, or if you’d just like to chat!",
          linkedin: "https://www.linkedin.com/in/harith-madani-osu/",
        },
        {
          name: "Dieynabou Diallo",
          position: "Professional Development",
          img: "images/eboard-photos/dieynabou-pic.jpg",
          bio: "Hi all! My name is Dieynabou Diallo and I’m the Professional Development Chair for ColorStack OSU. On the technical side I’ve had 5 technical internships including Microsoft as a SWE focusing on iOS Development. On the non-technical side I enjoy things such as cooking, poetry, trying cafes, and thrifting bags. Please feel free to reach out!",
          linkedin: "https://www.linkedin.com/in/dieynaboudiallo26/",
        },
        {
          name: "Ingrid Escalante-Hernandez",
          position: "Academic",
          img: "images/eboard-photos/ingrid-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ingridescher/",
        },
      ],
    },
    "2024-2025": {
      members: [
        {
          name: "Ephratah Meskel",
          position: "President",
          img: "images/eboard-photos/ephratah-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ephratahmh/",
        },
        {
          name: "Kwasi Fosu",
          position: "Vice President",
          img: "images/eboard-photos/kwasi-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/kwasi-sarfo-fosu-21a179255/",
        },
        {
          name: "Ahmed Nazar",
          position: "Secretary",
          img: "images/eboard-photos/ahmed-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ahmednmohamed/",
        },
        {
          name: "Mohamed Asmali",
          position: "Treasurer",
          img: "images/eboard-photos/asmali-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/mohamed-asmali/",
        },
        {
          name: "Mazin Tagelsir",
          position: "Operations",
          img: "images/eboard-photos/mazin-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/mazin-tagelsir/",
        },
        {
          name: "Hosanna Otchere",
          position: "Communications",
          img: "images/eboard-photos/hosanna-pic.jpg",
          bio: "Hi, my name is Hosanna Otchere, I am the Communications Chair.  I’ve had a few experiences, conducted research in video summarization, completed an internship at Mastercard, and I’m an Adobe Student Ambassador. Outside of that, I like wellness, music, and sometimes video editing. Hmu, if you have any questions about getting into research, internships, graphics, or video editing. ",
          linkedin: "https://www.linkedin.com/in/hosannaao/",
        },
        {
          name: "Nabeu Habetaslassa",
          position: "Corporate",
          img: "images/eboard-photos/nabeu-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/nabeu-habetaslassa-2a356b1b0/",
        },
        {
          name: "Ashley Holbrook",
          position: "Outreach",
          img: "images/eboard-photos/ashley-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ashleyholbrook/",
        },
        {
          name: "Jared Alonzo",
          position: "Professional Development",
          img: "images/eboard-photos/jared-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/jared-alonzo/",
        },
        {
          name: "Austen Young",
          position: "Web Development",
          img: "images/eboard-photos/austen-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/austenyoung/",
        },
      ],
    },
    "2023-2024": {
      members: [
        {
          name: "Ephratah Meskel",
          position: "President",
          img: "images/eboard-photos/ephratah-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ephratahmh/",
        },
        {
          name: "Mohamed Asmali",
          position: "Vice President",
          img: "images/eboard-photos/asmali-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/mohamed-asmali/",
        },
        {
          name: "Emmanuel Key",
          position: "Secretary",
          img: "images/eboard-photos/emanuel-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/emmanuelkey/",
        },
        {
          name: "Ahmed Nazar",
          position: "Treasurer",
          img: "images/eboard-photos/ahmed-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ahmednmohamed/",
        },
        {
          name: "Mazin Tagelsir",
          position: "Operations",
          img: "images/eboard-photos/mazin-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/mazin-tagelsir/",
        },
        {
          name: "Ugonna Obiagwu",
          position: "Communications",
          img: "images/eboard-photos/ugo-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ugonnaobiagwu/",
        },
        {
          name: "Olivia Alvarez",
          position: "Corporate",
          img: "images/eboard-photos/olivia-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/alvarez-olivia/",
        },
        {
          name: "Ashley Holbrook",
          position: "Outreach",
          img: "images/eboard-photos/ashley-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/ashleyholbrook/",
        },
        {
          name: "Edgar Sanchez",
          position: "Professional Development",
          img: "images/eboard-photos/edgar-pic.jpg",
          bio: "Fun fact here",
          linkedin: "https://www.linkedin.com/in/edgarsanchez25/",
        },
      ],
    },
  },
};

export default board;
