const events = [
  {
    id: "eos-event",
    name: ".atEOS( )",
    date: "April 15th, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "EOS Thumbnail",
    galleryTitle: ".atEOS() - April 15th",
    driveFolderId: "1RGEPYLUIY3fM6DZc3m5xqpBNzTLXPJUQ",
    driveThumbnailFileId: null,
  },
  {
    id: "godaddy-event",
    name: "GoDaddy",
    date: "September 23rd, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "GoDaddy Thumbnail",
    galleryTitle: "GoDaddy - September 23rd",
    driveFolderId: "1MwRC-NRr4nUJ8T1JgBNqeuZDbASXCEqe",
    driveThumbnailFileId: null,
  },
  {
    id: "eos-event",
    name: ".atEOS( )",
    date: "April 15th, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "EOS Thumbnail",
    galleryTitle: ".atEOS() - April 15th",
    driveFolderId: "1RGEPYLUIY3fM6DZc3m5xqpBNzTLXPJUQ",
    driveThumbnailFileId: null,
  },
  {
    id: "eos-event",
    name: ".atEOS( )",
    date: "April 15th, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "EOS Thumbnail",
    galleryTitle: ".atEOS() - April 15th",
    driveFolderId: "1RGEPYLUIY3fM6DZc3m5xqpBNzTLXPJUQ",
    driveThumbnailFileId: null,
  },
  {
    id: "eos-event",
    name: ".atEOS( )",
    date: "April 15th, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "EOS Thumbnail",
    galleryTitle: ".atEOS() - April 15th",
    driveFolderId: "1RGEPYLUIY3fM6DZc3m5xqpBNzTLXPJUQ",
    driveThumbnailFileId: null,
  },
  {
    id: "eos-event",
    name: ".atEOS( )",
    date: "April 15th, 2025",
    img: "images/event-photos/eos/eos-thumbnail.jpg",
    alt: "EOS Thumbnail",
    galleryTitle: ".atEOS() - April 15th",
    driveFolderId: "1RGEPYLUIY3fM6DZc3m5xqpBNzTLXPJUQ",
    driveThumbnailFileId: null,
  },
];

export default events;
